// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkynsyitenxhiesbqyyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxreW5zeWl0ZW54aGllc2JxeXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODk2NDcsImV4cCI6MjA1Nzk2NTY0N30.EYfX6pK82kI74-0maFiwslmnRlyPxBKu-Z8g9BL9J4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);