// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmvkjaczlmqdthnupfaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdmtqYWN6bG1xZHRobnVwZmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzI0MjUsImV4cCI6MjA1NzcwODQyNX0.Nh01OFZN4UrWBzChfsGNA3g4NCyV1XF2Ht5j1XKYnh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);