// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqnydmogduszlwgbjpxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxbnlkbW9nZHVzemx3Z2JqcHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTUwODYsImV4cCI6MjA1NzkzMTA4Nn0.fBD8Fy_-nnCW8Blo1_HqTrYMyYLcVyjbz7fj_5n_3K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);